import os
import numpy as np
import matplotlib.pyplot as plt
from pydmclab.plotting.utils import get_colors, set_rc_params, get_label
from pydmclab.plotting.utils import get_colors, set_rc_params, get_label
from matplotlib.ticker import MaxNLocator
from scipy.constants import physical_constants
from scipy.integrate import trapezoid


from pydmclab.utils.handy import read_json, write_json, convert_numpy_to_native
from pydmclab.core.struc import StrucTools
from pydmclab.core.comp import CompTools

from pymatgen.core.composition import Composition
from pymatgen.io.ase import AseAtomsAdaptor
from pymatgen.analysis.eos import Murnaghan, Vinet
from pymatgen.io.phonopy import get_phonopy_structure, get_pmg_structure

from phonopy import Phonopy

from ase.thermochemistry import CrystalThermo


set_rc_params()
COLORS = get_colors(palette="tab10")


class AnalyzePhonons(object):
    def __init__(self, unitcell: str|dict,
                 force_data: np.ndarray|list, 
                 primitive_matrix: list|str = "auto",
                 symprec=1e-5,
                 mesh: int|list|float=[30, 30, 30],
                 dataset: dict = None,
                 E0: float = 0,
                 init_kwargs: dict ={}
):
        """
        Class to analyze phonon data from a VASP calculation using Phonopy, Can return force constants, dynamical matrix, mesh data, thermal properties, band structure, and total density of states.
        Args:
            unitcell (str or dict):
                Path to the unitcell structure file (e.g., POSCAR) or structure as dict.
            force_data (array-like or list):
                List of forces from a set of displaced structures calculations. Shape=(N, natoms, 3) where N is the number of displacements and natoms is the number of atoms in the supercell.
                OR list of force constants. Shape=(natoms, natoms, 3, 3).
                WARNING: If you are using a dataset generated by phonopy.displacements, make sure the force_data is listing the forces from the displaced structures in the same order as the dataset.
            primitive_matrix (list):
                Transformation matrix from the unitcell to the primitive cell. e.g. [[0.5, 0, 0], [0, 0.5, 0], [0, 0, 1]] would reduce a 2x2x1 supercell to 1x1x1.
                Default is "auto", which will automatically reduce the results to the primitive cell.
                Set explicitly if want the results in terms of a different unitcell
            mesh (array-like or float):
                Mesh numbers along a, b, c axes when array_like object is given, shape=(3,).
                When float value is given, uniform mesh is generated following VASP convention by N = max(1, nint(l * |a|^*)) where 'nint' is the function to return the nearest integer. In this case, it is forced to set is_gamma_center=True.
                Default value is 100.0.
            dataset (dict):
                Only for Finite Displacement. Dictionary containing displacement information, can optionally include forces and supercell energy. But these can also be provided separately in force_data, this easier because you can just feed it as a list of arrays.
                Usually generated using phonopy's phonopy.displacements and then extract dataset using phonopy.dataset
                Helper function get_displacements_for_phonons() in hpc_worflows/phonon_calcs generates this for you as well.
                WARNING: See warning for force_data argument.
                Type 1. One atomic displacement in each supercell:
                {'natom': number of atoms in supercell,
                 'first_atoms': [
                   {'number': atom index of displaced atom,
                    'displacement': displacement in Cartesian coordinates,
                    'forces'(optional): forces on atoms in supercell,
                    'supercell_energy'(optional): energy of supercell},
                   {...}, ...]}
                There is a type 2 dataset for multiple displacements in each supercell, but this is not implemented here. Might look into it in the future if needed.
            E0 (float):
                In eV/atom.
                Optional static 0 K energy of the supercell. This is added to the phonon free energy to get the total free energy.
                If E0 is not provided, the Helmholtz free energy will only include the phonon contribution.
            init_kwargs:
                See https://github.com/phonopy/phonopy/blob/main/phonopy/api_phonopy.py for other init kwargs available
        """

        self.unitcell = StrucTools(unitcell).structure_as_dict
        self.force_data = force_data
        self.primitive_matrix = primitive_matrix
        self.dataset = dataset
        self.symprec = symprec
        self.E0 = E0

        if isinstance(mesh, (list, tuple)) and len(mesh) != 3:
            raise ValueError(
                "Mesh should be a list of three integers or an int."
            )

        self.pymatgen_struc = StrucTools(unitcell).structure
        self.natoms_unitcell = self.pymatgen_struc.num_sites 
        natoms_unitcell = self.natoms_unitcell 

        unitcell = get_phonopy_structure(self.pymatgen_struc) #PhonopyAtoms structure object

        phonon = Phonopy(unitcell=unitcell, primitive_matrix=primitive_matrix, symprec=symprec, **init_kwargs) 
        self.natoms = len(phonon.primitive) #natoms in primitive cell. results reported from phonopy are corresponding to number of atoms in the primitive. If you force it to not do a transformation to the primitive then phonon.primitive will correspond to whatever transformation you specified (whether it be the unitcell or another cell)
        phonon.dataset = dataset

        if force_data:
            arr = np.array(force_data)
            if arr.ndim == 3 and arr.shape[1:] == (natoms_unitcell, 3):
                # Looks like forces from displacements
                print(f"Detected forces from {arr.shape[0]} displacement calculations")
                self.forces = arr
                phonon.forces = arr 
                if phonon.dataset is None:
                    raise ValueError("Unable to set dataset for phonon calculation. Please provide a valid dataset or force constants.")
                phonon.produce_force_constants()
                self.force_constants = phonon.force_constants

            elif arr.shape == (natoms_unitcell, natoms_unitcell, 3, 3):
                # Looks like force constants
                print(f"Detected force constants in full form")
                phonon.force_constants = arr
                self.force_constants = phonon.force_constants
            else:
                raise ValueError(
                    f"Unrecognized force_data shape: {arr.shape}\n"
                    f"Expected one of:\n"
                    f"  - Forces: (N_displacements, {natoms_unitcell}, 3)\n"
                    f"  - Force constants: ({natoms_unitcell}, {natoms_unitcell}, 3, 3)\n"
                    f"\nBased on supercell with {natoms_unitcell} atoms"
                )

            # self.dynamical_matrix = phonon.dynamical_matrix # This is just a phonopy.dynamical_matrix.DynamicalMatrix object. Need it to run mesh.
            _mesh_out = phonon.run_mesh(mesh) #Need to run this in order to run everything else downstream

            self.phonon = phonon

        self._band_structure = None
        self._band_structure_paths = None

    @property
    def mesh_dict(self):
        """
        Returns the mesh data for the phonon object in a dictionary
        """
        mesh_dict = self.phonon.get_mesh_dict()
        return mesh_dict
    
    @property
    def find_high_symmetry_path(self):
        '''
        Find the high symmetry qpoints and corresponding coordinates for the given structure using seekpath.
        Returns:
                {
                ('Γ', 'X'): [[0.0, 0.0, 0.0], [0.5, 0.0, 0.0]],
                ('X', 'S'): [[0.5, 0.0, 0.0], [0.5, 0.5, 0.0]], ...
                }
        '''
        import seekpath
        structure = self.pymatgen_struc
        structure_tuple = (
            structure.lattice.matrix,
            structure.frac_coords,
            structure.atomic_numbers
        )
        path_data = seekpath.get_path(structure_tuple)
        path = path_data['path']
        
        out = {tuple(point.replace('GAMMA', 'Γ') for point in p): 
            [path_data['point_coords'][p[0]], path_data['point_coords'][p[1]]] 
            for p in path}
        
        return out

    def band_structure(
        self,
        paths: list|dict|None = None,
        Nq: int = 100
    ):
        """
        Returns the band structure for the phonon object in a dictionary
        Args:
            paths (list or dict or None):
                If None is provided, a path will automatically be found using seekpath
                List of paths in reciprocal space. e.g.: 
                            [
                                [[0.0, 0.0, 0.0], [0.5, 0.5, 0.0]],  # Γ to X 
                                [[0.5, 0.5, 1.0], [0, 0, 0]],  # X to K to Γ
                                [[0.0, 0.0, 0.0], [0.5, 0.5, 0.5]],  # Γ to L
                            ] (these coordinates/high symmetry points vary structure to structure)
                Or dictionary of paths with labels. e.g.:
                            {'Γ-X': [[0.0, 0.0, 0.0], [0.5, 0.5, 0.0]],
                            'X-Γ': [[0.5, 0.5, 1.0], [0, 0, 0]],...}
                            This will save the labels in the band structure dictionary for ease of plotting.

        Returns:
            {'qpoints': arrays of q points, 'distances': arrays of distances, 'frequencies': arrays of frequencies, 'eigenvectors': arrays of eigenvectors, group_velocities': arrays of group velocities, 'paths': list of path labels if provided or automatically found}
        """

        path_data = None
        if paths==None:
            path_data = self.find_high_symmetry_path
            paths = [path_data[key] for key in path_data]
        elif isinstance(paths, dict):
            path_data = paths
            paths = list(paths.values())

        def get_band(q_start, q_stop, N):
            """ Return path between q_start and q_stop """
            return np.array([q_start + (q_stop-q_start)*i/(N-1) for i in range(N)])

        bands = []
        for path in paths:
            qpoints = get_band(np.array(path[0]), np.array(path[1]), Nq)
            bands.append(qpoints)

        bands_equal = (
            len(self._band_structure_paths) == len(bands)
            and all(np.array_equal(a1, a2) for a1, a2 in zip(self._band_structure_paths, bands))
        ) if self._band_structure_paths else False

        if not bands_equal:
            print("Calculating band structure...")
            _ = self.phonon.run_band_structure(bands)
            self._band_structure_paths = bands        
            self._band_structure = self.phonon.get_band_structure_dict()
            if path_data is not None:
                self._band_structure['path'] = list(path_data.keys())

            h = physical_constants['Planck constant in eV/Hz'][0]
            # hbar = h / (2 * np.pi)
            freq_points = np.array(self._band_structure['frequencies'])
            #convert frequencies from THz to eV
            freq_points_ev = freq_points * 1e12 * h #I think it is not necessary to divide by 2pi here because phonopy already gives frequencies in Hz, not angular frequencies
            self._band_structure['frequencies'] = convert_numpy_to_native(freq_points_ev)

        return self._band_structure

    @property
    def total_dos(self):
        """
        Returns the total density of states for the phonon object in a dictionary.
        The units are converted from phonopy's default THz to eV!!
        Returns:
            {'E0' : 0 K internal energy (eV/atom),
            'total_dos' :
            [{'E' : energy level (eV), 'total_dos': total density of states}, ...],
            'units': {'frequency': 'eV', 'dos': 'states/eV', 'energy': 'eV/atom'}
            }
        """
        if not hasattr(self, '_total_dos'):
            print("Calculating total density of states...")
            _ = self.phonon.run_total_dos()
            total_dos = self.phonon.get_total_dos_dict()
            h = physical_constants['Planck constant in eV/Hz'][0]
            tdos = total_dos['total_dos']/(h*1e12) # This is to normalize the DOS to 1/eV (phonopy default is 1/THz)
            freq_points = total_dos['frequency_points']
            freq_points_ev = freq_points * 1e12 * h #convert frequencies from THz to eV
            self._total_dos = {
                'E0': self.E0,
                'total_dos': [{'E': E, 'total_dos': dos} for E, dos in zip(freq_points_ev, tdos)],
                'units': {'frequency': 'eV', 'dos': 'states/eV', 'energy': 'eV/atom'}
            }

        return self._total_dos

    def thermal_properties(self, temperatures=np.linspace(0, 2000, 101), 
                  include_heat_capacity: bool = True, 
                  move_imaginary: bool = False):
        """
        Helmholtz free energy calculated using ASE's CrystalThermo module.
        Args:
            temperatures (array-like):
                Array of temperatures in Kelvin at which to calculate the Helmholtz free energy.
            include_heat_capacity (bool):
                If True, includes heat capacity in the output.
            move_imaginary (bool):
                If True, moves imaginary frequencies to their absolute values.
                If False, removes imaginary frequencies from the DOS.
                In order to calculate thermodynamic properties, the phonon DOS must not contain imaginary frequencies, so it will always be cleaned.
        Returns:
            [{'T': 300, 
            'F': float,
            'S': float,
            'Cv': float}, ...]
            Units are eV/atom
        """
        phonon_dos = self.total_dos
        phonon_dos['E0'] = self.E0*self.natoms #Convert to eV/supercell for CrystalThermo
        normalize=self.natoms
        helmholtz = Helmholtz(phonon_dos=phonon_dos, temperatures=temperatures, normalize=normalize, move_imaginary=move_imaginary) #this will normalize to eV/atom not eV/formula unit
        F = helmholtz.helmholtz()
        if include_heat_capacity: 
            Cv = helmholtz.heat_capacity()
            for i in range(len(F['thermal_properties'])):
                F['thermal_properties'][i]['Cv'] = Cv['thermal_properties'][i]['Cv']
        return F

    def phonopy_thermal_properties(
        self,
        phonopy_tprops_kwargs=None,
        force_rerun: bool = False,
    ):
        """
        returns the thermal properties for the phonon object in a dictionary
        Args:
            phonopy_tprops_kwargs (dict, optional)
                see Phonopy.run_thermal_properties() for possible kwargs and defaults
            force_rerun (bool, optional)
                If you already ran thermal properties but now want to change some of the arguments
                and want it to recalculate the thermal properties, set this to True. Default is False.

        Returns parsed thermal properties:
        e.g. [{'temperature': 300, 'free_energy': float, 'entropy': float, 'heat_capacity': float},
                {'temperature': 310, 'free_energy': float, 'entropy': float, 'heat_capacity': float}, ...]
        """
        if force_rerun or not hasattr(self, '_thermal_properties'):
            print("Calculating phonopy thermal properties...")
            self.phonon.run_thermal_properties(**(phonopy_tprops_kwargs or {}))
            
            tp = self.phonon.get_thermal_properties_dict()
            if tp is not None:
                parsed_data = []

                temperatures = tp["temperatures"]
                free_energies = tp["free_energy"]
                entropies = tp["entropy"]
                heat_capacities = tp["heat_capacity"]

                for i, T in enumerate(temperatures):
                    data_point = {
                        "temperature": T,
                        "free_energy": free_energies[i],
                        "entropy": entropies[i],
                        "heat_capacity": heat_capacities[i],
                    }
                    parsed_data.append(data_point)

                self._thermal_properties = parsed_data
            else:
                print("Thermal properties could not be calculated.")
                return None
        
        return self._thermal_properties

    def summary(
        self,
        calc_dir: str = None,
        savename: str = "phonons.json",
        remake: bool = False,
        include_mesh: bool = False,
        include_force_constants: bool= False,
        include_band_structure = True,
        include_total_dos: bool = True,
        include_thermal_properties: bool = True,
        temperatures = np.linspace(0, 2000, 101),
        band_structure_kwargs: dict | None = None,
        include_phonopy_thermal_properties: bool = False,
        phonopy_tprops_kwargs: dict | None = None,
    ):
        """
        Returns all desired data for post-processing DFT calculations

        Args:
            calc_dir: 
                directory to save calculation results to. If None is provided, will not write.
            include_mesh (bool, optional):  
                Include mesh data in the output. Default is False because mesh data can be quite large.
            include_force_constants (bool, optional):
                Include force constants in the output. Default is True.
            include_band_structure (bool, optional):
                Include band structure in the output. Default is True.
                Remember, if want to set a custom path - need to give band_structure_kwargs
            include_total_dos (bool, optional):         
                Include total density of states in the output. Default is True.
            include_thermal_properties (bool, optional):
                Include thermal properties (F, S, Cv) in the output. Default is True.
            temperatures (list, array):
                Specify a range of temperatures for thermal properties, default is 0-2000.
            band_structure_kwargs (dict, optional): 
               Additional arguments for band structure calculation. See
               `self.band_structure` for details.
            include_phonopy_thermal_properties (bool, optional):
                If True, includes the thermal properties calculated using phonopy's built in functions in the output. Default is False.
                Note that these are in Phonopy's default units (usually THz for frequencies and eV/*primitive* cell for energies)
            phonopy_tprops_kwargs (dict):
                Additional arguments for phonopy thermal properties calculation. See
                `self.phonopy_thermal_properties` for details.

        Returns:
            Dictionary with the specified information
            {'force_constants': array of force constants, 'thermal_properties': dictionary of thermal properties, ....}

        """
        if calc_dir is not None:
            fjson = os.path.join(calc_dir, savename)
            if os.path.exists(fjson) and not remake:
                return read_json(fjson)
        
        data = {}
    
        if include_force_constants:
            fc = self.force_constants
            data["force_constants"] = fc

        if include_mesh:
            mesh_array = self.mesh_dict
            data["mesh"] = mesh_array

        if include_band_structure:
            band_struc = self.band_structure(**(band_structure_kwargs or {}))
            data["band_structure"] = band_struc

        if include_total_dos:
            total_dos = self.total_dos
            data["total_dos"] = total_dos

        if include_thermal_properties:
            helmholtz = self.thermal_properties(temperatures=temperatures,include_heat_capacity=True)
            data["thermal_properties"] = helmholtz

        if include_phonopy_thermal_properties:
            force_rerun = True if phonopy_tprops_kwargs else False
            tp = self.phonopy_thermal_properties(phonopy_tprops_kwargs, force_rerun=force_rerun)
            data["phonopy_thermal_properties"] = tp

        data = convert_numpy_to_native(data)  # Convert to JSON serializable format

        if calc_dir is not None:
            write_json(data, fjson)
            return read_json(fjson)
        else:
            return data

    #Plotting functions are just using phonopy's built in plotting functions, use plotting functions in pydmclab.plotting.phonons for more customizable functions
    @property
    def plot_thermal_properties_phonopy(self):
        self.phonopy_thermal_properties() #If thermal properties haven't been calculated, calculations will be done with defaults
        self.phonon.plot_thermal_properties()

    @property
    def plot_band_structure(self, qpoints=None, frequencies=None, labels=None, 
                                ylabel="Frequency (eV)", figsize=(8, 6)):
        if self._band_structure is None:
            self.band_structure()       
        self.phonon.plot_band_structure()

    @property
    def plot_total_dos(self):
        self.total_dos
        self.phonon.plot_total_dos()
    
    @property
    def plot_band_structure_and_dos(self):
        if self._band_structure is None:
            self.band_structure()
        self.total_dos
        self.phonon.plot_band_structure_and_dos()

class Helmholtz():

    def __init__(self, phonon_dos, temperatures=np.linspace(0, 2000, 101), normalize = None, move_imaginary: bool = False):
        """
            Args:
                phonon_dos (Usually obtained from the phonon_dos method of the AnalyzePhonons class, 
                which gets it from AnalyzePhonons.total_dos):
                    {'E0' : 0 K internal energy (eV/cell),
                    'total_dos' :
                        [{'E' : energy level (eV),
                        'total_dos' : phonon DOS at E (float)}]
                        }

                    E0 is optional, but if not given, the energy given is only from phonons, not including the static 0 K energy.
                    ** Units should be in eV for frequencies, states/eV for DOS and eV/cell for E0 (where cell corresponds to the cell size used to calculate the DOS). 
                    If E0 is in eV/atom, make sure to multiply by number of atoms in cell before feeding it here, otherwise it will be doubly normalized.**

                temperatures (np.array)
                    list of temperatures (K)

                normalize (int)
                    What you want to normalize by. If None is given, the energy will be in eV/cell. 
                    If a number is given, the energy will be divided by that number.
                    Could give number of formula units to get eV/formula unit, or number of atoms to get eV/atom.
                move_imaginary (bool):
                    If True, moves imaginary frequencies to their absolute values.
                    If False, removes imaginary frequencies from the DOS.
                    In order to calculate thermodynamic properties, the phonon DOS must not contain imaginary frequencies, so it will always be cleaned.
        """


        self.phonon_dos = phonon_dos
        self.temperatures = temperatures
        self.normalize = normalize
        self.E0 = phonon_dos["E0"] if "E0" in phonon_dos else 0
        self.move_imaginary = move_imaginary


    def cleanup_dos(self, move_imaginary: bool = False):
        """
        Cleans up the phonon DOS by removing or adjusting imaginary frequencies.
        Args:
            move_imaginary (bool):
                If True, moves imaginary frequencies to their absolute values.
                If False, removes imaginary frequencies from the DOS.
        """
        if hasattr(self, 'clean_dos') and self.clean_dos['move_imaginary']==move_imaginary:
            return self.clean_dos
        phonon_dos = self.phonon_dos
        frequency_points = np.array([phonon_dos['total_dos'][i]['E'] for i in range(len(phonon_dos['total_dos']))])
        total_dos = np.array([phonon_dos['total_dos'][i]['total_dos'] for i in range(len(phonon_dos['total_dos']))])
        negative_freqs_with_0_dos = [i for i, freq in enumerate(frequency_points) if freq < 0 and total_dos[i] == 0]

        if move_imaginary:
            # Move imaginary frequencies to their absolute values
            filtered_frequencies = np.abs(frequency_points)
            filtered_dos = total_dos
            print(f"Moved {np.sum(frequency_points < 0)} imaginary frequencies to their absolute values.")
        else:
            # Remove all DOS values and frequencies where there are imaginary frequencies
            valid_indices = [
                i for i, freq in enumerate(frequency_points)
                if np.real(freq) > 0
            ]
            filtered_frequencies = frequency_points[valid_indices]
            filtered_dos = total_dos[valid_indices]
            print(f"Removed {len(frequency_points) - len(filtered_frequencies)} imaginary frequencies from the DOS. "
                  f"{len(negative_freqs_with_0_dos)} of them had zero DOS.")

        self.clean_dos = {
            'E0': self.E0,
            'total_dos': {'frequencies':filtered_frequencies, 'total_dos':filtered_dos},
            'units': phonon_dos.get('units', 'eV'),
            'move_imaginary':move_imaginary
        }
        return self.clean_dos


    def thermo(self):
        phonon_dos = self.cleanup_dos(move_imaginary=self.move_imaginary)
        E0 = self.E0
        normalize = self.normalize

        return CrystalThermo(
            phonon_energies=phonon_dos['total_dos']['frequencies'],
            phonon_DOS=phonon_dos['total_dos']['total_dos'],
            potentialenergy=E0,
            formula_units=normalize,
        )

    def zero_point_energy(self):
        phonon_dos = self.cleanup_dos(move_imaginary=self.move_imaginary)
        normalize = self.normalize
        E0 = self.E0
        phonon_energies = phonon_dos['total_dos']['frequencies']
        dos_values = phonon_dos['total_dos']['total_dos']
        zpe_list = phonon_energies / 2.
        zpe = trapezoid(zpe_list * dos_values, phonon_energies)
        if normalize is None:
            return (zpe + E0)
        else:
            return (zpe + E0)/normalize
    
    def helmholtz(self):
        """
        Returns:
            list
                [{'T': temperature (K), 'F': Helmholtz free energy (eV/cell or eV/self.normalize), 'S': entropy (J/mol/K)}]
        """
        thermo = self.thermo()
        temperatures = self.temperatures

        S = [0.0 if T == 0 
             else thermo.get_entropy(temperature=T) 
             for T in temperatures] #Entropy is zero at 0 K
        
        Fs = [self.zero_point_energy() if T == 0 
              else thermo.get_helmholtz_energy(temperature=T) 
              for T in temperatures] #Helmholtz free energy includes ZPE at 0 K

        out = {
            "thermal_properties": [
                {"T": temperatures[i], "F": Fs[i], "S": S[i]} for i in range(len(temperatures))
            ]
        }
        return out    

    def heat_capacity(self):
        """
        Calculate heat capacity at constant volume from phonon DOS
        """
        phonon_dos = self.cleanup_dos(move_imaginary=self.move_imaginary)
        temperatures = self.temperatures
        normalize = self.normalize
        
        phonon_energies = phonon_dos['total_dos']['frequencies']
        dos_values = phonon_dos['total_dos']['total_dos']
        
        kB = physical_constants['Boltzmann constant in eV/K'][0]
        
        Cv_list = []
        for T in temperatures:
            if T == 0:
                Cv_list.append(0.0)
            else:
                x = phonon_energies / (kB * T)
                x = np.clip(x, -500, 500)
                exp_x = np.exp(x)
                
                # Heat capacity formula: Cv = kB * (x²·exp(x)) / (exp(x)-1)²
                numerator = x**2 * exp_x
                denominator = (exp_x - 1)**2
                
                # Avoid division by zero
                mask = denominator > 1e-10
                integrand = np.zeros_like(x)
                integrand[mask] = numerator[mask] / denominator[mask]
                
                Cv = kB * trapezoid(integrand * dos_values, phonon_energies)
                
                if normalize is not None:
                    Cv = Cv / normalize
                    
                Cv_list.append(Cv)
        
        return {
            "thermal_properties": [
                {"T": temperatures[i], "Cv": Cv_list[i]} 
                for i in range(len(temperatures))
            ]
        }

class Gibbs():
    def __init__(self, helmholtz_dict, 
                 eos="vinet",):
    
        '''
        Args:
            helmholtz_dict (dict):
                {volume (float) :
                    {
                    'thermal_properties' :
                        [{'T' : temperature (K),
                        'F' : helmholtz free energy at T (eV/atom)}]                      
                    }
                }
                NOTE: F values should be total energy including BOTH 0 K DFT energy and phonon contribution (E_DFT(V) + F_phonon(V,T))
            eos (str):
                equation of state to use for fitting the data. Default is "vinet".
            temperatures (np.array):
                list of temperatures (K)
        '''
        self.eos = eos
        self.helmholtz_dict = helmholtz_dict

    @property
    def volumes(self):
        return list(self.helmholtz_dict.keys())
    
    @property
    def temperatures(self):
        first_vol = self.volumes[0]
        return [i['T'] for i in self.helmholtz_dict[first_vol]['thermal_properties']]

    def gibbs(self):
        """
        Returns:
            dict
            {
              'data': [{'T': K, 'G': eV/atom, 'V': Å³}, ...],
              'eos_curves': {
                    'volume_grid': array of volumes (Å³),
                    'F_vs_volume': {T: array of F values}
            }
        """
        eos = self.eos
        volumes = self.volumes
        temperatures = self.temperatures
        Fs = self.helmholtz_dict
        Gs = []
        fitted_F_values = {}

        V = [float(vol) for vol in volumes]
        smooth_volumes = np.linspace(min(V), max(V), 500) # Generate a smooth range of volumes to save for plotting

        for i in range(len(temperatures)):
            T = temperatures[i]
            F = [Fs[vol]["thermal_properties"][i]["F"] for vol in volumes]
            print(f"T = {T}, F = {F}")
            print(V)

            if eos == "vinet":
                current_eos = Vinet(V, F)
            elif eos == "murnaghan":
                current_eos = Murnaghan(V, F)
            else:
                print(f"Invalid EOS: {eos}. Using Vinet EOS instead.")
                current_eos = Vinet(V, F)

            try:
                current_eos.fit()
                min_F = current_eos.e0
                V_eq = current_eos.v0
                Gs.append({"T": T, "G": min_F, "V": V_eq})
                print(f"T = {T}, eos.e0 = {current_eos.e0}, parameters = {current_eos.eos_params}")
 
                fitted_F_values[T] = current_eos.func(smooth_volumes) 

            except Exception as e:
                print(f"Failed to fit {eos} EOS at T = {T} K: {e}")
                continue
        
        eos_curves = {"F_vs_volume": fitted_F_values, "volume_grid": smooth_volumes}

        return {"data": Gs, "eos_curves": eos_curves}
    

class QHA(object):
    def __init__(self, 
                 data_dict: dict, 
                 temperatures = np.linspace(0, 2000, 101), 
                 eos: str = "vinet",
                 ap_kwargs = None,):
        
        '''
        Args:
            data_dict (dict):
                {volume (float) :
                    {'structure' : structure dictionary,
                    'force_data': array of forces or force constants
                    'dataset': dataset generated by phonopy if using finite displacement 
                    'E0' : 0 K internal energy (eV/atom),
                    'total_dos' (optional):
                        [{'E' : energy level (eV),
                        'total_dos' : phonon DOS at E (float)}]
                        }
                NOTE: if dos is given, then force_data and data_set are not needed. DOS needs to correspond to structure size given!
                     if dos is not given, then force data and dataset will be needed to calculate dos and consequently thermal properties.
            temperatures (list):
                list of temperatures (K)
            eos (str):
                equation of state to use for fitting the data. Default is "vinet"
            ap_kwargs (dict):
                kwargs for initializing AnalyzePhonons

        '''
        
        self.data_dict = data_dict
        self.temperatures = temperatures
        self.eos = eos
        self._ap_kwargs = ap_kwargs or {}
        self._analyzers = {}
        self._summaries = {}


    @property
    def structures(self):
        """
        Returns:
            dictionary where keys are tuples of (formula, mpid) with lists of isotropically strained structures as values,
            e.g.
            {('Al1N1', 'mp-661'): [list of strained structures]}
        """
        data_dict = self.data_dict
        structures = [data_dict[volume]['structure'] 
                              for volume in data_dict]
        return structures

    @property
    def volumes(self):
        """
        Returns:
            dict: list of volumes
        """
        volumes = list(self.data_dict.keys())
        return volumes
    
    @property
    def natoms(self) -> int:
        return len(self.structures[0]['sites'])

    @property
    def formula_units(self) -> float:
        formula = StrucTools(self.structures[0]).formula
        _, factor = Composition(formula).get_reduced_composition_and_factor()
        return factor

    def _get_analyzer(self, vol) -> AnalyzePhonons:
        if vol not in self._analyzers:
            entry = self.data_dict[vol]
            self._analyzers[vol] = AnalyzePhonons(
                unitcell=entry['structure'],
                force_data=entry.get('force_data'),
                dataset=entry.get('dataset'),
                E0=entry['E0'],
                **self._ap_kwargs
            )
        return self._analyzers[vol]

    def _get_summary(self, vol) -> dict:
        if vol not in self._summaries:
            self._summaries[vol] = self._get_analyzer(vol).summary(
                temperatures=self.temperatures
            )
        return self._summaries[vol]

    @property
    def total_dos(self) -> dict:
        result = {}
        for vol in self.volumes:
            entry = self.data_dict[vol]
            if 'total_dos' in entry:
                result[vol] = {'E0': entry['E0'], 'total_dos': entry['total_dos']}
            else:
                result[vol] = self._get_summary(vol)['total_dos']
        return result

    def helmholtz(self, move_imaginary: bool = False) -> dict:
        result = {}
        for vol in self.volumes:
            entry = self.data_dict[vol]
            if 'total_dos' in entry:
                dos = self.total_dos[vol]
                E0_per_cell = dos['E0'] * self.natoms
                f = Helmholtz(
                    phonon_dos={**dos, 'E0': E0_per_cell},
                    temperatures=self.temperatures,
                    normalize=self.natoms,
                    move_imaginary=move_imaginary,
                ).helmholtz()
                result[vol] = {'thermal_properties': f['thermal_properties']}
            else:
                result[vol] = {'thermal_properties': self._get_summary(vol)['thermal_properties']}
        return result
    
    def gibbs(self, eos="vinet", move_imaginary: bool = False):
            """
            Returns:
            {
              'data': [{'T': K, 'G': eV/atom, 'V': Å³}, ...],
              'eos_curves': {
                    'volume_grid': array of volumes (Å³),
                    'F_vs_volume': {T: array of F values}
            }
            """

            G = Gibbs(self.helmholtz(move_imaginary=move_imaginary), eos=eos).gibbs()
            return G

    def qha_dict(self, write=False, data_dir=os.getcwd().replace("scripts", "data"), savename="qha.json", remake=False):
        """
        Returns:
            A dictionary with QHA information for all structures.
            e.g. {'Al1N1': {'mp-661': [list of QHA info dictionaries]}}
        """
        fjson = os.path.join(data_dir, savename)
        if not remake and os.path.exists(fjson) and write:
            return read_json(fjson)
        
        gibbs = self.gibbs()
        helmholtz = self.helmholtz()
        dos = self.total_dos

        qha_dict = {
                    "volume_resolved": {
                        dos,
                        helmholtz,
                    },
                    "gibbs": gibbs
                }   

        if write:
            write_json(qha_dict, fjson)
            return read_json(fjson)
        return qha_dict

"""
To do: 
make sure the structures that are taken in are consistent and properly formatted across the helper functions.
also ensure that the outputs are in a consistent format.
"""