execute_flags:
- srun
- python
- lobster
- bader
- mpirun
files_to_inherit:
- WAVECAR
- CONTCAR
force_postprocess: false
fqueue: q.o
fresh_restart: false
machine: msi
manager: '#SBATCH'
mpi_command: mpirun
packing:
  gga:
  - gga-loose
  - gga-relax
  - gga-static
  ggau:
  - ggau-loose
  - ggau-relax
  - ggau-static
  metagga:
  - gga-loose
  - gga-relax
  - gga-static
  - metagga-relax
  - metagga-static
perturb_first_struc: 0.1
vasp: vasp_std
