# VASPSetUp (general)
# see VASPTools.VASPSetUp for what these mean
standard: dmc # make mp if comparing to MP data
xc: gga # gga, ggau, or metagga
fun: default # usually this is fine
mag: fm # **change** as desired
calc: relax # usually this is what we want unless you want an independent "static" or "loose" calc
potcar_functional: PBE_54 # probably don't change
validate_magmom: False # probably don't change
lobster_static: True # can make False if you don't want to run LOBSTER
mag_override: False # if True, allows user to run nm calcs for mag systems and vice versa

# may be desirable to pass various configs for each type of calculation
# INCARs should be {INCAR_FLAG : value}
# KPOINTs should be Kpoints object
# POTCARs should be {el (str) : potcar flag (str)}

# loose calculations
loose_INCAR: {}
loose_KPOINTS: 
loose_POTCAR:

# relax calculations
relax_INCAR: {}
relax_KPOINTS: 
relax_POTCAR:

# static calculations
static_INCAR: {}
static_KPOINTS:
static_POTCAR: